# Generated by Django 5.2.8 on 2026-01-10 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('auth_url', models.URLField(verbose_name='Auth URL')),
                ('leads_url', models.URLField(verbose_name='Leads URL')),
            ],
            options={
                'verbose_name': 'Partner App',
                'verbose_name_plural': 'Partner Apps',
            },
        ),
        migrations.CreateModel(
            name='PartnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('login', models.CharField(max_length=255, verbose_name='Login')),
                ('session_data', models.JSONField(blank=True, default=dict, verbose_name='Session Data')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='partner.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Account',
                'verbose_name_plural': 'Partner Accounts',
                'unique_together': {('user', 'login', 'app')},
            },
        ),
        migrations.CreateModel(
            name='PartnerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, verbose_name='External ID')),
                ('lead_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('updated_ts', models.DateTimeField(blank=True, null=True, verbose_name='Updated TS')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('target_city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Status')),
                ('eats_order_number', models.CharField(blank=True, max_length=255, verbose_name='Order Number')),
                ('rewarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Rewarded At')),
                ('closed_reason', models.CharField(blank=True, max_length=255, verbose_name='Closed Reason')),
                ('utm_campaign', models.CharField(blank=True, max_length=255, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(blank=True, max_length=255, verbose_name='UTM Content')),
                ('utm_medium', models.CharField(blank=True, max_length=255, verbose_name='UTM Medium')),
                ('utm_source', models.CharField(blank=True, max_length=255, verbose_name='UTM Source')),
                ('utm_term', models.CharField(blank=True, max_length=255, verbose_name='UTM Term')),
                ('creator_username', models.CharField(blank=True, max_length=255, verbose_name='Creator')),
                ('reward', models.CharField(blank=True, max_length=255, verbose_name='Reward')),
                ('complaint_status', models.CharField(blank=True, max_length=255, verbose_name='Complaint Status')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='partner.partneraccount')),
            ],
            options={
                'verbose_name': 'Partner Lead',
                'verbose_name_plural': 'Partner Leads',
                'unique_together': {('account', 'external_id')},
            },
        ),
    ]
