# Generated by Django 5.2.8 on 2026-01-08 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0001_initial'),
        ('sender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField()),
                ('crm_category_id', models.PositiveIntegerField()),
                ('assign_by_id', models.PositiveIntegerField()),
                ('source_id', models.CharField(max_length=100)),
                ('employers', models.ManyToManyField(related_name='bitrixes', to='hh.employer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
